{% set name = "rio-ui" %}
{% set version = "0.10.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rio_ui-{{ version }}.tar.gz
  sha256: 5b939eca734d60d79ec1b38069a945640c5e0b9662623d7fd56ad249041d5b93

build:
  entry_points:
    - rio = rio.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - hatchling
    - pip
  run:
    - python >=3.10
    - fastapi >=0.110,<1.dev0
    - fuzzywuzzy >=0.18,<1.dev0
    - gitignore-parser ==0.1.11
    - httpx >=0.27.2,<0.28.0.dev0
    - imy >=0.4.0
    - introspection >=1.9,<2.dev0
    - isort >=5.13,<6.dev0
    - keyring >=24.3,<25.dev0
    - pillow >=10.2,<11.dev0
    - python-levenshtein >=0.23,<1.dev0
    - python-multipart >=0.0.6,<0.1.dev0
    - pytz >=2024.1,<2025.dev0
    - revel >=0.9.1,<0.10.dev0
    - timer-dict >=1.0,<2.dev0
    - tomlkit >=0.12,<1.dev0
    - typing-extensions >=4.5
    - unicall >=0.1.5,<0.2.dev0
    - uniserde >=0.3.14,<0.4.dev0
    - uvicorn-standard >=0.29.0,<0.30.dev0
    - watchfiles >=0.21,<1.dev0
    - yarl >=1.9
    - langcodes >=3.4.0
    - crawlerdetect >=0.1.7,<0.2.dev0
    - ordered-set >=4.1.0

test:
  imports:
    - rio
  commands:
    - pip check
    - rio help
  requires:
    - pip

about:
  home: https://github.com/rio-labs/rio
  doc_url: https://rio.dev/
  summary: Build modern Websites and Apps just with Python
  license: Apache-2.0
  license_file:
    - LICENSE.txt
    - rio/assets/fonts/Roboto/LICENSE.txt
    - rio/assets/fonts/Roboto Mono/LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
