{% set name = "rio-ui" %}
{% set version = "0.11.1" %}
{% set python_min = "3.10 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rio_ui-{{ version }}.tar.gz
  sha256: e30de85d3c5534097e4a0ff9aaa13ae16e28b27c590ce4857390bdbf0e80a6d6

build:
  entry_points:
    - rio = rio.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling ==1.26.3
    - pip
  run:
    - python >={{ python_min }}
    - crawlerdetect >=0.1.7,<0.2.dev0
    - fastapi >=0.110,<1.dev0
    - fuzzywuzzy >=0.18,<1.dev0
    - gitignore-parser ==0.1.11
    - imy ==0.6.1
    - introspection >=1.9.9,<1.10.dev0
    - isort >=5.13,<6.dev0
    - keyring >=24.3,<25.dev0
    - langcodes >=3.4,<4.dev0
    - narwhals >=1.12,<2.dev0
    - ordered-set >=4.1,<5.dev0
    - path-imports >=1.1.2,<1.2.dev0
    - pillow >=10.2,<11.dev0
    - python-levenshtein >=0.23,<1.dev0
    - pytz >=2024.1,<2025.dev0
    - revel >=0.9.1,<0.10.dev0
    - timer-dict >=1.0,<2.dev0
    - tomlkit >=0.12,<1.dev0
    - typing_extensions >=4.5,<5.dev0
    - unicall >=0.1.5,<0.2.dev0
    - uniserde >=0.3.14,<0.4.dev0
    - uvicorn-standard >=0.29.0,<0.30.dev0
    - watchfiles >=0.21,<1.dev0
    - yarl >=1.9
    - python-multipart >=1.2,<2.dev0

    # Needed by imy[docstrings,deprecations]
    # All fulfilled by depedencies

test:
  imports:
    - rio
  commands:
    - pip check
    - rio help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/rio-labs/rio
  doc_url: https://rio.dev/
  summary: Build modern Websites and Apps just with Python
  license: Apache-2.0
  license_file:
    - LICENSE.txt
    - rio/assets/fonts/Roboto/LICENSE.txt
    - rio/assets/fonts/Roboto Mono/LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
